package UI;

import Main_Package.Controleur;
import java.awt.Color;
import Main_Package.Etagere;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SABOU350
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        getContentPane().setBackground(Color.WHITE); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        AfficheurContainer = new javax.swing.JPanel();
        afficheur = new UI.AfficheurEtagere2D();
        jPanel1 = new javax.swing.JPanel();
        AddMontantHorizontal_button = new javax.swing.JButton();
        AddMontantVertical_button = new javax.swing.JButton();
        DeleteMontant_Button = new javax.swing.JButton();
        Undo_Buitton = new javax.swing.JButton();
        Redo_Button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Hauteur_Textfield = new javax.swing.JTextField();
        Hauteur_Label = new javax.swing.JLabel();
        Hauteur_Cmlabel = new javax.swing.JLabel();
        Largeur_Label = new javax.swing.JLabel();
        Largeur_Cmlabel = new javax.swing.JLabel();
        Largeur_TextField = new javax.swing.JTextField();
        Profondeur_TextField = new javax.swing.JTextField();
        Profondeur_CMlabel = new javax.swing.JLabel();
        Profondeur_Label = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        EpaisseurTriple_Field = new javax.swing.JTextField();
        EpaisseurTriple_Mesure = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EpaisseurDouble_Field = new javax.swing.JTextField();
        EpaisseurDouble_Mesure = new javax.swing.JLabel();
        PerimatreTriple_Radio = new javax.swing.JRadioButton();
        PerimetreDouble_Radio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Metrique_Button = new javax.swing.JRadioButton();
        Imperial_Button = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PPiece_Cmlabel = new javax.swing.JLabel();
        HPiece_Cmlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LargeurPieceSelecrtionneField = new javax.swing.JTextField();
        HauteurPieceSelecrtionneField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ProfondeurPieceSelecrtionneField = new javax.swing.JTextField();
        LPiece_Cmlabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HauteurRelEtage_Field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        LargeurRelCaisson_Field = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuBtnNouveau = new javax.swing.JMenuItem();
        MenuSauvegarder = new javax.swing.JMenuItem();
        MenuCharger = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        exporterListePieces = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        STLEtagere = new javax.swing.JMenuItem();
        STLPiecesIndividuelles = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("3Dtagère");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);
        setName("MainWindow"); // NOI18N
        setPreferredSize(new java.awt.Dimension(739, 500));

        AfficheurContainer.setBackground(new java.awt.Color(255, 255, 255));

        Controleur.getInstance().setAfficheur(afficheur);
        afficheur.setBackground(new java.awt.Color(245, 245, 245));
        afficheur.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout afficheurLayout = new javax.swing.GroupLayout(afficheur);
        afficheur.setLayout(afficheurLayout);
        afficheurLayout.setHorizontalGroup(
            afficheurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );
        afficheurLayout.setVerticalGroup(
            afficheurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AfficheurContainerLayout = new javax.swing.GroupLayout(AfficheurContainer);
        AfficheurContainer.setLayout(AfficheurContainerLayout);
        AfficheurContainerLayout.setHorizontalGroup(
            AfficheurContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfficheurContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(afficheur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AfficheurContainerLayout.setVerticalGroup(
            AfficheurContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfficheurContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(afficheur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        AddMontantHorizontal_button.setBackground(new java.awt.Color(3, 169, 244));
        AddMontantHorizontal_button.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        AddMontantHorizontal_button.setForeground(new java.awt.Color(255, 255, 255));
        AddMontantHorizontal_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/horizontale.png"))); // NOI18N
        AddMontantHorizontal_button.setText("Horizontal");
        AddMontantHorizontal_button.setBorderPainted(false);
        AddMontantHorizontal_button.setFocusPainted(false);
        AddMontantHorizontal_button.setIconTextGap(6);
        AddMontantHorizontal_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMontantHorizontal_buttonMouseClicked(evt);
            }
        });
        AddMontantHorizontal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMontantHorizontal_buttonActionPerformed(evt);
            }
        });

        AddMontantVertical_button.setBackground(new java.awt.Color(3, 169, 244));
        AddMontantVertical_button.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        AddMontantVertical_button.setForeground(new java.awt.Color(255, 255, 255));
        AddMontantVertical_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/verticale.png"))); // NOI18N
        AddMontantVertical_button.setText("Verticale");
        AddMontantVertical_button.setBorderPainted(false);
        AddMontantVertical_button.setFocusPainted(false);
        AddMontantVertical_button.setIconTextGap(6);
        AddMontantVertical_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMontantVertical_buttonMouseClicked(evt);
            }
        });
        AddMontantVertical_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMontantVertical_buttonActionPerformed(evt);
            }
        });

        DeleteMontant_Button.setBackground(new java.awt.Color(244, 67, 54));
        DeleteMontant_Button.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        DeleteMontant_Button.setForeground(new java.awt.Color(255, 255, 255));
        DeleteMontant_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/delete.png"))); // NOI18N
        DeleteMontant_Button.setText("Supprimer");
        DeleteMontant_Button.setBorderPainted(false);
        DeleteMontant_Button.setFocusPainted(false);
        DeleteMontant_Button.setIconTextGap(6);
        DeleteMontant_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMontant_ButtonMouseClicked(evt);
            }
        });
        DeleteMontant_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMontant_ButtonActionPerformed(evt);
            }
        });

        Undo_Buitton.setBackground(new java.awt.Color(255, 87, 34));
        Undo_Buitton.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        Undo_Buitton.setForeground(new java.awt.Color(255, 255, 255));
        Undo_Buitton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/undo.png"))); // NOI18N
        Undo_Buitton.setText("Undo");
        Undo_Buitton.setActionCommand("Imperial ou metrique");
        Undo_Buitton.setBorderPainted(false);
        Undo_Buitton.setFocusPainted(false);
        Undo_Buitton.setIconTextGap(6);
        Undo_Buitton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Undo_BuittonActionPerformed(evt);
            }
        });

        Redo_Button.setBackground(new java.awt.Color(255, 87, 34));
        Redo_Button.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        Redo_Button.setForeground(new java.awt.Color(255, 255, 255));
        Redo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/redo.png"))); // NOI18N
        Redo_Button.setText("Redo");
        Redo_Button.setActionCommand("Imperial ou metrique");
        Redo_Button.setBorderPainted(false);
        Redo_Button.setFocusPainted(false);
        Redo_Button.setIconTextGap(6);
        Redo_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Redo_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(AddMontantHorizontal_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddMontantVertical_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteMontant_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Undo_Buitton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Redo_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddMontantHorizontal_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(AddMontantVertical_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(DeleteMontant_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Undo_Buitton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Redo_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Maison Neue", 1, 24)); // NOI18N
        jLabel12.setText("Étagère");

        Hauteur_Textfield.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        Hauteur_Textfield.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Hauteur_TextfieldCaretUpdate(evt);
            }
        });
        Hauteur_Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hauteur_TextfieldActionPerformed(evt);
            }
        });
        Hauteur_Textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Hauteur_TextfieldKeyPressed(evt);
            }
        });

        Hauteur_Label.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        Hauteur_Label.setText("Hauteur");

        Hauteur_Cmlabel.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        Hauteur_Cmlabel.setText("cm");

        Largeur_Label.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        Largeur_Label.setText("Largeur");

        Largeur_Cmlabel.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        Largeur_Cmlabel.setText("cm");

        Largeur_TextField.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        Largeur_TextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Largeur_TextFieldCaretUpdate(evt);
            }
        });
        Largeur_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Largeur_TextFieldActionPerformed(evt);
            }
        });
        Largeur_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Largeur_TextFieldKeyPressed(evt);
            }
        });

        Profondeur_TextField.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        Profondeur_TextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Profondeur_TextFieldCaretUpdate(evt);
            }
        });
        Profondeur_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Profondeur_TextFieldKeyPressed(evt);
            }
        });

        Profondeur_CMlabel.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        Profondeur_CMlabel.setText("cm");

        Profondeur_Label.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        Profondeur_Label.setText("Profondeur");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Maison Neue", 1, 14)); // NOI18N
        jLabel9.setText("Épaisseur du périmètre");
        jLabel9.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Maison Neue", 1, 14)); // NOI18N
        jLabel13.setText("Options");

        jCheckBox1.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        jCheckBox1.setText("Panneau de fond");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        jCheckBox2.setText("Dépasse");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        jLabel10.setText("Épaisseur d'un panneau triple");

        EpaisseurTriple_Field.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N

        EpaisseurTriple_Mesure.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        EpaisseurTriple_Mesure.setText("Po");

        jLabel11.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        jLabel11.setText("Épaisseur d'un panneau double");

        EpaisseurDouble_Field.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        EpaisseurDouble_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EpaisseurDouble_FieldActionPerformed(evt);
            }
        });

        EpaisseurDouble_Mesure.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        EpaisseurDouble_Mesure.setText("Po");

        buttonGroup1.add(PerimatreTriple_Radio);
        PerimatreTriple_Radio.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        PerimatreTriple_Radio.setText("Triple");
        PerimatreTriple_Radio.setToolTipText("");
        PerimatreTriple_Radio.setActionCommand("");
        PerimatreTriple_Radio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PerimatreTriple_RadioStateChanged(evt);
            }
        });
        PerimatreTriple_Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerimatreTriple_RadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(PerimetreDouble_Radio);
        PerimetreDouble_Radio.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        PerimetreDouble_Radio.setSelected(true);
        PerimetreDouble_Radio.setText("Double");
        PerimetreDouble_Radio.setToolTipText("");
        PerimetreDouble_Radio.setActionCommand("");
        PerimetreDouble_Radio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PerimetreDouble_RadioStateChanged(evt);
            }
        });
        PerimetreDouble_Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerimetreDouble_RadioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Maison Neue", 1, 14)); // NOI18N
        jLabel1.setText("Dimensions");

        jLabel7.setFont(new java.awt.Font("Maison Neue", 1, 14)); // NOI18N
        jLabel7.setText("Unités");
        jLabel7.setToolTipText("");

        buttonGroup2.add(Metrique_Button);
        Metrique_Button.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        Metrique_Button.setSelected(true);
        Metrique_Button.setText("Métrique");
        Metrique_Button.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Metrique_ButtonStateChanged(evt);
            }
        });
        Metrique_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Metrique_ButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(Imperial_Button);
        Imperial_Button.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        Imperial_Button.setText("Impérial");
        Imperial_Button.setToolTipText("");
        Imperial_Button.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Imperial_ButtonStateChanged(evt);
            }
        });
        Imperial_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imperial_ButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        jLabel2.setText("Hauteur");

        PPiece_Cmlabel.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        PPiece_Cmlabel.setText("cm");

        HPiece_Cmlabel.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        HPiece_Cmlabel.setText("cm");

        jLabel3.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        jLabel3.setText("Largeur");

        LargeurPieceSelecrtionneField.setEditable(false);
        LargeurPieceSelecrtionneField.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        LargeurPieceSelecrtionneField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        LargeurPieceSelecrtionneField.setBorder(null);

        HauteurPieceSelecrtionneField.setEditable(false);
        HauteurPieceSelecrtionneField.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        HauteurPieceSelecrtionneField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        HauteurPieceSelecrtionneField.setToolTipText("");
        HauteurPieceSelecrtionneField.setBorder(null);
        HauteurPieceSelecrtionneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HauteurPieceSelecrtionneFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Maison Neue", 1, 14)); // NOI18N
        jLabel5.setText("Dimensions de la pièce sélectionnée");

        ProfondeurPieceSelecrtionneField.setEditable(false);
        ProfondeurPieceSelecrtionneField.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        ProfondeurPieceSelecrtionneField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ProfondeurPieceSelecrtionneField.setBorder(null);
        ProfondeurPieceSelecrtionneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfondeurPieceSelecrtionneFieldActionPerformed(evt);
            }
        });
        ProfondeurPieceSelecrtionneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProfondeurPieceSelecrtionneFieldKeyPressed(evt);
            }
        });

        LPiece_Cmlabel.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        LPiece_Cmlabel.setText("cm");

        jLabel4.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        jLabel4.setText("Profondeur");

        jLabel14.setFont(new java.awt.Font("Maison Neue", 1, 24)); // NOI18N
        jLabel14.setText("Sélection");

        jLabel6.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        jLabel6.setText("Hauteur relative de l'étage");

        HauteurRelEtage_Field.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        HauteurRelEtage_Field.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HauteurRelEtage_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HauteurRelEtage_FieldActionPerformed(evt);
            }
        });
        HauteurRelEtage_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HauteurRelEtage_FieldKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        jLabel8.setText("Largeur relative du caisson");

        LargeurRelCaisson_Field.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N
        LargeurRelCaisson_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LargeurRelCaisson_FieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HauteurRelEtage_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ProfondeurPieceSelecrtionneField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PPiece_Cmlabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(HauteurPieceSelecrtionneField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HPiece_Cmlabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(LargeurPieceSelecrtionneField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LPiece_Cmlabel))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(LargeurRelCaisson_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(HauteurRelEtage_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LargeurRelCaisson_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(HauteurPieceSelecrtionneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HPiece_Cmlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LargeurPieceSelecrtionneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(LPiece_Cmlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfondeurPieceSelecrtionneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(PPiece_Cmlabel)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Metrique_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Imperial_Button))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PerimatreTriple_Radio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PerimetreDouble_Radio))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Hauteur_Label)
                                    .addComponent(Largeur_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Profondeur_Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Hauteur_Textfield)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Profondeur_CMlabel))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Largeur_TextField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Hauteur_Cmlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Profondeur_TextField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Largeur_Cmlabel))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EpaisseurTriple_Field)
                                    .addComponent(EpaisseurDouble_Field))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EpaisseurDouble_Mesure)
                                    .addComponent(EpaisseurTriple_Mesure, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PerimatreTriple_Radio)
                    .addComponent(PerimetreDouble_Radio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hauteur_Label)
                    .addComponent(Hauteur_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profondeur_CMlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Largeur_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hauteur_Cmlabel)
                    .addComponent(Largeur_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Profondeur_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profondeur_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Largeur_Cmlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Metrique_Button)
                    .addComponent(Imperial_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EpaisseurDouble_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EpaisseurDouble_Mesure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EpaisseurTriple_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EpaisseurTriple_Mesure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Hauteur_Label.getAccessibleContext().setAccessibleDescription("");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 234, 234)));
        jMenuBar1.setFont(new java.awt.Font("Maison Neue", 0, 14)); // NOI18N

        jMenu1.setText("Fichier");

        MenuBtnNouveau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuBtnNouveau.setText("Nouvelle Etagere...");
        MenuBtnNouveau.setToolTipText("");
        MenuBtnNouveau.setActionCommand("");
        MenuBtnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBtnNouveauActionPerformed(evt);
            }
        });
        jMenu1.add(MenuBtnNouveau);

        MenuSauvegarder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        MenuSauvegarder.setText("Sauvegarder");
        MenuSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSauvegarderActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSauvegarder);

        MenuCharger.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        MenuCharger.setText("Ouvrir...");
        MenuCharger.setToolTipText("");
        MenuCharger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuChargerActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCharger);

        jMenuItem2.setText("Quitter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exporter");

        exporterListePieces.setText("Liste des pièces");
        exporterListePieces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exporterListePiecesActionPerformed(evt);
            }
        });
        jMenu2.add(exporterListePieces);

        jMenuItem5.setText("Plan de coupe");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        STLEtagere.setText("Modèle 3D de l'étagère");
        STLEtagere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STLEtagereActionPerformed(evt);
            }
        });
        jMenu2.add(STLEtagere);

        STLPiecesIndividuelles.setText("Modèle 3D des pièces");
        STLPiecesIndividuelles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STLPiecesIndividuellesActionPerformed(evt);
            }
        });
        jMenu2.add(STLPiecesIndividuelles);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AfficheurContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AfficheurContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private boolean DoesValueGoOverThreshold(String inputValue) {
        if (inputValue.length() == 0) {
            return false;
        }
        Double value = Double.parseDouble(inputValue);
        if (!Metrique_Button.isSelected()) {
            value *= 2.54;
        }
        return (value > Etagere.MAX_SIZE);
    }
    public JTextField getLargeurRelCaisson_Field() {
        return LargeurRelCaisson_Field;
    }

    public void setLargeurRelCaisson_Field(JTextField LargeurRelCaisson_Field) {
        this.LargeurRelCaisson_Field = LargeurRelCaisson_Field;
    }

    public JTextField getHauteurRelEtage_Field() {
        return HauteurRelEtage_Field;
    }

    public void setHauteurRelEtage_Field(JTextField HauteurRelEtage_Field) {
        this.HauteurRelEtage_Field = HauteurRelEtage_Field;
    }

    public JLabel getHauteur_Label() {
        return Hauteur_Label;
    }

    public void setHauteur_Label(JLabel Hauteur_Label) {
        this.Hauteur_Label = Hauteur_Label;
    }

    private void AddMontantHorizontal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMontantHorizontal_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMontantHorizontal_buttonActionPerformed

    private void DeleteMontant_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMontant_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteMontant_ButtonActionPerformed

    private void Redo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Redo_ButtonActionPerformed
        Controleur.getInstance().redo();
    }//GEN-LAST:event_Redo_ButtonActionPerformed

    private void Undo_BuittonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Undo_BuittonActionPerformed
        Controleur.getInstance().undo();
    }//GEN-LAST:event_Undo_BuittonActionPerformed

    private void AddMontantVertical_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMontantVertical_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMontantVertical_buttonActionPerformed

    private void MenuBtnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBtnNouveauActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
             @Override
             public void run() {
                promptCreerEtagere();
             }
        });
    }//GEN-LAST:event_MenuBtnNouveauActionPerformed

    private void MenuSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSauvegarderActionPerformed
        JFileChooser explorer = new JFileChooser();
        int ack = explorer.showSaveDialog(null);
        if (JFileChooser.APPROVE_OPTION == ack) {
                try {
                    FileOutputStream fileout = new FileOutputStream(explorer.getSelectedFile().toString()+".ser");
//                    FileOutputStream fileout = new FileOutputStream("test.ser");
                    ObjectOutputStream out = new ObjectOutputStream(fileout);
                    out.writeObject(Controleur.getInstance().getEtagere());
                    out.close();
                    fileout.close();                
                } catch (Exception ex) {
                }
        }
        
    }//GEN-LAST:event_MenuSauvegarderActionPerformed

    private void MenuChargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuChargerActionPerformed
        
        JFileChooser explorer = new JFileChooser();
        int ack = explorer.showSaveDialog(null);
        if (JFileChooser.APPROVE_OPTION == ack) {
            try {
                FileInputStream fileIn = new FileInputStream(explorer.getSelectedFile().toString());
                ObjectInputStream in = new ObjectInputStream(fileIn);
                Etagere etagerechargee = (Etagere) in.readObject();
                Controleur.getInstance().setEtagere(etagerechargee);
                in.close();
                fileIn.close();
            } catch (IOException | ClassNotFoundException i) {
            }
        }
    }//GEN-LAST:event_MenuChargerActionPerformed

    private void exporterListePiecesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exporterListePiecesActionPerformed
        String liste = Controleur.getInstance().getStrListePieces();
        JFileChooser explorer = new JFileChooser();
        int ack = explorer.showSaveDialog(null);
        if (JFileChooser.APPROVE_OPTION == ack) {
            try {
                FileWriter writer = new FileWriter(explorer.getSelectedFile()+".txt");
                writer.write(liste);
                writer.close();
            } catch (Exception ex) {
                return;
            }
        }
    }//GEN-LAST:event_exporterListePiecesActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JFileChooser explorer = new JFileChooser();
        int ack = explorer.showSaveDialog(null);

        if (JFileChooser.APPROVE_OPTION == ack) {
            try {
                Controleur.getInstance().getPlanDeCoupe(explorer.getSelectedFile());

            }catch(Exception ex){
                
            }
        }
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    private void AddMontantHorizontal_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMontantHorizontal_buttonMouseClicked
        Controleur.getInstance().setAjouteetageMode(true);
        if(Controleur.getInstance().isAjouteCaissonMode() == true){
            Controleur.getInstance().setAjouteCaissonMode(false);
            
        }
        
    }//GEN-LAST:event_AddMontantHorizontal_buttonMouseClicked

    private void AddMontantVertical_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMontantVertical_buttonMouseClicked
        if(Controleur.getInstance().isAjouteCaissonMode()){
            Controleur.getInstance().setAjouteCaissonMode(false);
        }
        if(Controleur.getInstance().isAjouteCaissonMode() == false){
            Controleur.getInstance().setAjouteCaissonMode(true);
        }
        if(Controleur.getInstance().isAjouteetageMode()){
            Controleur.getInstance().setAjouteetageMode(false);
        }
    }//GEN-LAST:event_AddMontantVertical_buttonMouseClicked

    private void DeleteMontant_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMontant_ButtonMouseClicked
        if(Controleur.getInstance().getMontantVerticalSelectionne() != null){
            Controleur.getInstance().SupprimeMontantVertical();
        }
        else if(Controleur.getInstance().getMontantEtageHorizontalSelectionne() != null){
            Controleur.getInstance().SupprimeMontantHorizontal();
        }
    }//GEN-LAST:event_DeleteMontant_ButtonMouseClicked

    private void ProfondeurPieceSelecrtionneFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProfondeurPieceSelecrtionneFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Controleur.getInstance().setEtagereProfondeur(Double.parseDouble(getLargeur_TextField().getText()));
            Controleur.getInstance().getAfficheur().redraw();
        }
    }//GEN-LAST:event_ProfondeurPieceSelecrtionneFieldKeyPressed

    private void ProfondeurPieceSelecrtionneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfondeurPieceSelecrtionneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfondeurPieceSelecrtionneFieldActionPerformed

    private void EpaisseurDouble_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EpaisseurDouble_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EpaisseurDouble_FieldActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        if(jCheckBox2.isSelected()){
            Controleur.getInstance().setDepasse(true);
        }
        if(jCheckBox2.isSelected()){
            Controleur.getInstance().setDepasse(false);
        }
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void LargeurRelCaisson_FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LargeurRelCaisson_FieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Controleur.getInstance().setLrelativeCaissonSelectionne(Double.parseDouble(LargeurRelCaisson_Field.getText()));
        }
    }//GEN-LAST:event_LargeurRelCaisson_FieldKeyPressed

    private void HauteurRelEtage_FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HauteurRelEtage_FieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Controleur.getInstance().setHrelativeEtageSelectionnee(Double.parseDouble(HauteurRelEtage_Field.getText()));
        }
    }//GEN-LAST:event_HauteurRelEtage_FieldKeyPressed

    private void HauteurRelEtage_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HauteurRelEtage_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HauteurRelEtage_FieldActionPerformed

    private void Hauteur_TextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Hauteur_TextfieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (DoesValueGoOverThreshold(getHauteur_Textfield().getText())) {
                JOptionPane.showMessageDialog(null, "The value you entered is too high, the maximum is " + Etagere.MAX_SIZE + " cm", "Whoops",
                                   JOptionPane.ERROR_MESSAGE);
            } else {
                Controleur.getInstance().setEtagereHauteur(Double.parseDouble(getHauteur_Textfield().getText()));
                Controleur.getInstance().getAfficheur().redraw();
            }
        }
    }//GEN-LAST:event_Hauteur_TextfieldKeyPressed

    private void Hauteur_TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hauteur_TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hauteur_TextfieldActionPerformed

    private void Largeur_TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Largeur_TextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (DoesValueGoOverThreshold(getLargeur_TextField().getText())) {
                JOptionPane.showMessageDialog(null, "The value you entered is too high, the maximum is " + Etagere.MAX_SIZE + " cm", "Whoops",
                                   JOptionPane.ERROR_MESSAGE);
            } else {
                Controleur.getInstance().setEtagereLargeur(Double.parseDouble(getLargeur_TextField().getText()));
                Controleur.getInstance().getAfficheur().redraw();
            }
        }
    }//GEN-LAST:event_Largeur_TextFieldKeyPressed

    private void Largeur_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Largeur_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Largeur_TextFieldActionPerformed

    private void PerimatreTriple_RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerimatreTriple_RadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerimatreTriple_RadioActionPerformed

    private void PerimatreTriple_RadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PerimatreTriple_RadioStateChanged
        if(PerimatreTriple_Radio.isSelected()){
            Controleur.getInstance().setTriple(true);
        }
    }//GEN-LAST:event_PerimatreTriple_RadioStateChanged

    private void PerimetreDouble_RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerimetreDouble_RadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerimetreDouble_RadioActionPerformed

    private void PerimetreDouble_RadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PerimetreDouble_RadioStateChanged
        if(PerimetreDouble_Radio.isSelected()){
            Controleur.getInstance().setTriple(false);
        }
    }//GEN-LAST:event_PerimetreDouble_RadioStateChanged

    private void Imperial_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imperial_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Imperial_ButtonActionPerformed

    private void Imperial_ButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Imperial_ButtonStateChanged
        if(Imperial_Button.isSelected()){
            Hauteur_Cmlabel.setText("Po");
            Largeur_Cmlabel.setText("Po");
            Profondeur_CMlabel.setText("Po");
            HPiece_Cmlabel.setText("Po");
            LPiece_Cmlabel.setText("Po");
            PPiece_Cmlabel.setText("Po");
            Controleur.getInstance().updatevuImperiale();
        }
    }//GEN-LAST:event_Imperial_ButtonStateChanged

    private void Metrique_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Metrique_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Metrique_ButtonActionPerformed

    private void Metrique_ButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Metrique_ButtonStateChanged
        if(Metrique_Button.isSelected()){
            Hauteur_Cmlabel.setText("cm");
            Largeur_Cmlabel.setText("cm");
            Profondeur_CMlabel.setText("cm");
            HPiece_Cmlabel.setText("cm");
            LPiece_Cmlabel.setText("cm");
            PPiece_Cmlabel.setText("cm");
            Controleur.getInstance().updatevue();
        }
    }//GEN-LAST:event_Metrique_ButtonStateChanged

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void STLEtagereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STLEtagereActionPerformed
        Controleur.getInstance().getSTL();
    }//GEN-LAST:event_STLEtagereActionPerformed

    private void STLPiecesIndividuellesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STLPiecesIndividuellesActionPerformed
        Controleur.getInstance().getIndividualSTL();
    }//GEN-LAST:event_STLPiecesIndividuellesActionPerformed

    private void Profondeur_TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Profondeur_TextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (DoesValueGoOverThreshold(getProfondeur_TextField().getText())) {
                JOptionPane.showMessageDialog(null, "The value you entered is too high, the maximum is " + Etagere.MAX_SIZE + " cm", "Whoops",
                                   JOptionPane.ERROR_MESSAGE);
            } else {
                Controleur.getInstance().setEtagereProfondeur(Double.parseDouble(getProfondeur_TextField().getText()));
                Controleur.getInstance().getAfficheur().redraw();
            }
        }
    }//GEN-LAST:event_Profondeur_TextFieldKeyPressed

    private void Hauteur_TextfieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Hauteur_TextfieldCaretUpdate
        if(DoesValueGoOverThreshold(Hauteur_Textfield.getText())) {
            Hauteur_Textfield.setBackground(Color.red);
        } else {
            Hauteur_Textfield.setBackground(Color.white);
        }
    }//GEN-LAST:event_Hauteur_TextfieldCaretUpdate

    private void Largeur_TextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Largeur_TextFieldCaretUpdate
        if(DoesValueGoOverThreshold(Hauteur_Textfield.getText())) {
            Largeur_TextField.setBackground(Color.red);
        } else {
            Largeur_TextField.setBackground(Color.white);
        }
    }//GEN-LAST:event_Largeur_TextFieldCaretUpdate

    private void Profondeur_TextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Profondeur_TextFieldCaretUpdate
        if(DoesValueGoOverThreshold(Hauteur_Textfield.getText())) {
            Profondeur_TextField.setBackground(Color.red);
        } else {
            Profondeur_TextField.setBackground(Color.white);
        }
    }//GEN-LAST:event_Profondeur_TextFieldCaretUpdate

    private void HauteurPieceSelecrtionneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HauteurPieceSelecrtionneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HauteurPieceSelecrtionneFieldActionPerformed

    public static void promptCreerEtagere() {
        CreateNewEtagereWindow popup2 = new CreateNewEtagereWindow();
        popup2.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                GUI gui = new GUI();
                gui.setVisible(true);
                Controleur.getInstance().setVue(gui);
                promptCreerEtagere();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMontantHorizontal_button;
    private javax.swing.JButton AddMontantVertical_button;
    private javax.swing.JPanel AfficheurContainer;
    private javax.swing.JButton DeleteMontant_Button;
    private javax.swing.JTextField EpaisseurDouble_Field;
    private javax.swing.JLabel EpaisseurDouble_Mesure;
    private javax.swing.JTextField EpaisseurTriple_Field;
    private javax.swing.JLabel EpaisseurTriple_Mesure;
    private javax.swing.JLabel HPiece_Cmlabel;
    private javax.swing.JTextField HauteurPieceSelecrtionneField;
    private javax.swing.JTextField HauteurRelEtage_Field;
    private javax.swing.JLabel Hauteur_Cmlabel;
    private javax.swing.JLabel Hauteur_Label;
    private javax.swing.JTextField Hauteur_Textfield;
    private javax.swing.JRadioButton Imperial_Button;
    private javax.swing.JLabel LPiece_Cmlabel;
    private javax.swing.JTextField LargeurPieceSelecrtionneField;
    private javax.swing.JTextField LargeurRelCaisson_Field;
    private javax.swing.JLabel Largeur_Cmlabel;
    private javax.swing.JLabel Largeur_Label;
    private javax.swing.JTextField Largeur_TextField;
    private javax.swing.JMenuItem MenuBtnNouveau;
    private javax.swing.JMenuItem MenuCharger;
    private javax.swing.JMenuItem MenuSauvegarder;
    private javax.swing.JRadioButton Metrique_Button;
    private javax.swing.JLabel PPiece_Cmlabel;
    private javax.swing.JRadioButton PerimatreTriple_Radio;
    private javax.swing.JRadioButton PerimetreDouble_Radio;
    private javax.swing.JTextField ProfondeurPieceSelecrtionneField;
    private javax.swing.JLabel Profondeur_CMlabel;
    private javax.swing.JLabel Profondeur_Label;
    private javax.swing.JTextField Profondeur_TextField;
    private javax.swing.JButton Redo_Button;
    private javax.swing.JMenuItem STLEtagere;
    private javax.swing.JMenuItem STLPiecesIndividuelles;
    private javax.swing.JButton Undo_Buitton;
    private UI.AfficheurEtagere2D afficheur;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JMenuItem exporterListePieces;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    public JTextField getHauteur_Textfield() {
        return Hauteur_Textfield;
    }

    public JButton getAddMontantHorizontal_button() {
        return AddMontantHorizontal_button;
    }

    public void setAddMontantHorizontal_button(JButton AddMontantHorizontal_button) {
        this.AddMontantHorizontal_button = AddMontantHorizontal_button;
    }

    public JButton getAddMontantVertical_button() {
        return AddMontantVertical_button;
    }

    public void setAddMontantVertical_button(JButton AddMontantVertical_button) {
        this.AddMontantVertical_button = AddMontantVertical_button;
    }

    public JButton getDeleteMontant_Button() {
        return DeleteMontant_Button;
    }

    public void setDeleteMontant_Button(JButton DeleteMontant_Button) {
        this.DeleteMontant_Button = DeleteMontant_Button;
    }

    public JTextField getEpaisseurDouble_Field() {
        return EpaisseurDouble_Field;
    }

    public void setEpaisseurDouble_Field(JTextField EpaisseurDouble_Field) {
        this.EpaisseurDouble_Field = EpaisseurDouble_Field;
    }

    public JLabel getEpaisseurDouble_Mesure() {
        return EpaisseurDouble_Mesure;
    }

    public void setEpaisseurDouble_Mesure(JLabel EpaisseurDouble_Mesure) {
        this.EpaisseurDouble_Mesure = EpaisseurDouble_Mesure;
    }

    public JTextField getEpaisseurTriple_Field() {
        return EpaisseurTriple_Field;
    }

    public void setEpaisseurTriple_Field(JTextField EpaisseurTriple_Field) {
        this.EpaisseurTriple_Field = EpaisseurTriple_Field;
    }

    public JLabel getEpaisseurTriple_Mesure() {
        return EpaisseurTriple_Mesure;
    }

    public void setEpaisseurTriple_Mesure(JLabel EpaisseurTriple_Mesure) {
        this.EpaisseurTriple_Mesure = EpaisseurTriple_Mesure;
    }

    public JLabel getHPiece_Cmlabel() {
        return HPiece_Cmlabel;
    }

    public void setHPiece_Cmlabel(JLabel HPiece_Cmlabel) {
        this.HPiece_Cmlabel = HPiece_Cmlabel;
    }

    public JLabel getHauteur_Cmlabel() {
        return Hauteur_Cmlabel;
    }

    public void setHauteur_Cmlabel(JLabel Hauteur_Cmlabel) {
        this.Hauteur_Cmlabel = Hauteur_Cmlabel;
    }

    public JRadioButton getImperial_Button() {
        return Imperial_Button;
    }

    public void setImperial_Button(JRadioButton Imperial_Button) {
        this.Imperial_Button = Imperial_Button;
    }

    public JLabel getLPiece_Cmlabel() {
        return LPiece_Cmlabel;
    }

    public void setLPiece_Cmlabel(JLabel LPiece_Cmlabel) {
        this.LPiece_Cmlabel = LPiece_Cmlabel;
    }

    public JLabel getLargeur_Cmlabel() {
        return Largeur_Cmlabel;
    }

    public void setLargeur_Cmlabel(JLabel Largeur_Cmlabel) {
        this.Largeur_Cmlabel = Largeur_Cmlabel;
    }

    public JMenuItem getMenuCharger() {
        return MenuCharger;
    }

    public void setMenuCharger(JMenuItem MenuCharger) {
        this.MenuCharger = MenuCharger;
    }

    public JMenuItem getMenuSauvegarder() {
        return MenuSauvegarder;
    }

    public void setMenuSauvegarder(JMenuItem MenuSauvegarder) {
        this.MenuSauvegarder = MenuSauvegarder;
    }

    public JRadioButton getMetrique_Button() {
        return Metrique_Button;
    }

    public void setMetrique_Button(JRadioButton Metrique_Button) {
        this.Metrique_Button = Metrique_Button;
    }

    public JLabel getPPiece_Cmlabel() {
        return PPiece_Cmlabel;
    }

    public void setPPiece_Cmlabel(JLabel PPiece_Cmlabel) {
        this.PPiece_Cmlabel = PPiece_Cmlabel;
    }

    public JRadioButton getPerimatreTriple_Radio() {
        return PerimatreTriple_Radio;
    }

    public void setPerimatreTriple_Radio(JRadioButton PerimatreTriple_Radio) {
        this.PerimatreTriple_Radio = PerimatreTriple_Radio;
    }

    public JRadioButton getPerimetreDouble_Radio() {
        return PerimetreDouble_Radio;
    }

    public void setPerimetreDouble_Radio(JRadioButton PerimetreDouble_Radio) {
        this.PerimetreDouble_Radio = PerimetreDouble_Radio;
    }

    public JLabel getProfondeur_CMlabel() {
        return Profondeur_CMlabel;
    }

    public void setProfondeur_CMlabel(JLabel Profondeur_CMlabel) {
        this.Profondeur_CMlabel = Profondeur_CMlabel;
    }

    public JButton getRedo_Button() {
        return Redo_Button;
    }

    public void setRedo_Button(JButton Redo_Button) {
        this.Redo_Button = Redo_Button;
    }

    public JButton getUndo_Buitton() {
        return Undo_Buitton;
    }

    public void setUndo_Buitton(JButton Undo_Buitton) {
        this.Undo_Buitton = Undo_Buitton;
    }

    public AfficheurEtagere2D getAfficheur() {
        return afficheur;
    }

    public void setAfficheur(AfficheurEtagere2D afficheur) {
        this.afficheur = afficheur;
    }

    public JMenuItem getExporterListePieces() {
        return exporterListePieces;
    }

    public void setExporterListePieces(JMenuItem exporterListePieces) {
        this.exporterListePieces = exporterListePieces;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }
    

    public void setHauteur_Textfield(JTextField Hauteur_Textfield) {
        this.Hauteur_Textfield = Hauteur_Textfield;
    }

    public JTextField getLargeur_TextField() {
        return Largeur_TextField;
    }

    public void setLargeur_TextField(JTextField Largeur_TextField) {
        this.Largeur_TextField = Largeur_TextField;
    }

    public JTextField getProfondeur_TextField() {
        return Profondeur_TextField;
    }

    public void setProfondeur_TextField(JTextField Profondeur_TextField) {
        this.Profondeur_TextField = Profondeur_TextField;
    }

    /**
     * @return the AfficheurContainer
     */
    public javax.swing.JPanel getAfficheurContainer() {
        return AfficheurContainer;
    }

    /**
     * @param AfficheurContainer the AfficheurContainer to set
     */
    public void setAfficheurContainer(javax.swing.JPanel AfficheurContainer) {
        this.AfficheurContainer = AfficheurContainer;
    }

    /**
     * @return the EpaisseurPieceSelecrtionneField
     */
    public javax.swing.JTextField getProfondeurPieceSelecrtionneField() {
        return ProfondeurPieceSelecrtionneField;
    }

    /**
     * @param EpaisseurPieceSelecrtionneField the EpaisseurPieceSelecrtionneField to set
     */
    public void setProfondeurPieceSelecrtionneField(javax.swing.JTextField EpaisseurPieceSelecrtionneField) {
        this.ProfondeurPieceSelecrtionneField = EpaisseurPieceSelecrtionneField;
    }

    /**
     * @return the HauteurPieceSelecrtionneField
     */
    public javax.swing.JTextField getHauteurPieceSelecrtionneField() {
        return HauteurPieceSelecrtionneField;
    }

    /**
     * @param HauteurPieceSelecrtionneField the HauteurPieceSelecrtionneField to set
     */
    public void setHauteurPieceSelecrtionneField(javax.swing.JTextField HauteurPieceSelecrtionneField) {
        this.HauteurPieceSelecrtionneField = HauteurPieceSelecrtionneField;
    }

    /**
     * @return the LargeurPieceSelecrtionneField
     */
    public javax.swing.JTextField getLargeurPieceSelecrtionneField() {
        return LargeurPieceSelecrtionneField;
    }

    /**
     * @param LargeurPieceSelecrtionneField the LargeurPieceSelecrtionneField to set
     */
    public void setLargeurPieceSelecrtionneField(javax.swing.JTextField LargeurPieceSelecrtionneField) {
        this.LargeurPieceSelecrtionneField = LargeurPieceSelecrtionneField;
    }

    /**
     * @return the Largeur_Label
     */
    public javax.swing.JLabel getLargeur_Label() {
        return Largeur_Label;
    }

    /**
     * @param Largeur_Label the Largeur_Label to set
     */
    public void setLargeur_Label(javax.swing.JLabel Largeur_Label) {
        this.Largeur_Label = Largeur_Label;
    }

    /**
     * @return the MenuBtnNouveau
     */
    public javax.swing.JMenuItem getMenuBtnNouveau() {
        return MenuBtnNouveau;
    }

    /**
     * @param MenuBtnNouveau the MenuBtnNouveau to set
     */
    public void setMenuBtnNouveau(javax.swing.JMenuItem MenuBtnNouveau) {
        this.MenuBtnNouveau = MenuBtnNouveau;
    }

    /**
     * @return the Profondeur_Label
     */
    public javax.swing.JLabel getProfondeur_Label() {
        return Profondeur_Label;
    }

    /**
     * @param Profondeur_Label the Profondeur_Label to set
     */
    public void setProfondeur_Label(javax.swing.JLabel Profondeur_Label) {
        this.Profondeur_Label = Profondeur_Label;
    }
    
    /**
     * @return the buttonGroup1
     */
    public javax.swing.ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    /**
     * @param buttonGroup1 the buttonGroup1 to set
     */
    public void setButtonGroup1(javax.swing.ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    /**
     * @return the buttonGroup2
     */
    public javax.swing.ButtonGroup getButtonGroup2() {
        return buttonGroup2;
    }

    /**
     * @param buttonGroup2 the buttonGroup2 to set
     */
    public void setButtonGroup2(javax.swing.ButtonGroup buttonGroup2) {
        this.buttonGroup2 = buttonGroup2;
    }

    /**
     * @return the jButton21
     */
    public javax.swing.JButton getjButton21() {
        return Redo_Button;
    }

    /**
     * @param jButton21 the jButton21 to set
     */
    public void setjButton21(javax.swing.JButton jButton21) {
        this.Redo_Button = jButton21;
    }

    /**
     * @return the jButton22
     */
    public javax.swing.JButton getjButton22() {
        return Undo_Buitton;
    }

    /**
     * @param jButton22 the jButton22 to set
     */
    public void setjButton22(javax.swing.JButton jButton22) {
        this.Undo_Buitton = jButton22;
    }

    /**
     * @return the jButton5
     */
    public javax.swing.JButton getjButton5() {
        return DeleteMontant_Button;
    }

    /**
     * @param jButton5 the jButton5 to set
     */
    public void setjButton5(javax.swing.JButton jButton5) {
        this.DeleteMontant_Button = jButton5;
    }

    /**
     * @return the jButton6
     */
    public javax.swing.JButton getjButton6() {
        return AddMontantVertical_button;
    }

    /**
     * @param jButton6 the jButton6 to set
     */
    public void setjButton6(javax.swing.JButton jButton6) {
        this.AddMontantVertical_button = jButton6;
    }


    /**
     * @return the jButton8
     */
    public javax.swing.JButton getjButton8() {
        return AddMontantHorizontal_button;
    }

    /**
     * @param jButton8 the jButton8 to set
     */
    public void setjButton8(javax.swing.JButton jButton8) {
        this.AddMontantHorizontal_button = jButton8;
    }

    /**
     * @return the jCheckBox1
     */
    public javax.swing.JCheckBox getjCheckBox1() {
        return jCheckBox1;
    }

    /**
     * @param jCheckBox1 the jCheckBox1 to set
     */
    public void setjCheckBox1(javax.swing.JCheckBox jCheckBox1) {
        this.jCheckBox1 = jCheckBox1;
    }

    /**
     * @return the jCheckBox2
     */
    public javax.swing.JCheckBox getjCheckBox2() {
        return jCheckBox2;
    }

    /**
     * @param jCheckBox2 the jCheckBox2 to set
     */
    public void setjCheckBox2(javax.swing.JCheckBox jCheckBox2) {
        this.jCheckBox2 = jCheckBox2;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    

    /**
     * @return the jMenu1
     */
    public javax.swing.JMenu getjMenu1() {
        return jMenu1;
    }

    /**
     * @param jMenu1 the jMenu1 to set
     */
    public void setjMenu1(javax.swing.JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    /**
     * @return the jMenu2
     */
    public javax.swing.JMenu getjMenu2() {
        return jMenu2;
    }

    /**
     * @param jMenu2 the jMenu2 to set
     */
    public void setjMenu2(javax.swing.JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    /**
     * @return the jMenuBar1
     */
    public javax.swing.JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    /**
     * @param jMenuBar1 the jMenuBar1 to set
     */
    public void setjMenuBar1(javax.swing.JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    /**
     * @return the jMenuItem1
     */
    public javax.swing.JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    /**
     * @param jMenuItem1 the jMenuItem1 to set
     */
    public void setjMenuItem1(javax.swing.JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    /**
     * @return the jMenuItem3
     */
    public javax.swing.JMenuItem getjMenuItem3() {
        return MenuSauvegarder;
    }

    /**
     * @param jMenuItem3 the jMenuItem3 to set
     */
    public void setjMenuItem3(javax.swing.JMenuItem jMenuItem3) {
        this.MenuSauvegarder = jMenuItem3;
    }

    /**
     * @return the jMenuItem4
     */
    public javax.swing.JMenuItem getjMenuItem4() {
        return exporterListePieces;
    }

    /**
     * @param jMenuItem4 the jMenuItem4 to set
     */
    public void setjMenuItem4(javax.swing.JMenuItem jMenuItem4) {
        this.exporterListePieces = jMenuItem4;
    }

    /**
     * @return the jMenuItem5
     */
    public javax.swing.JMenuItem getjMenuItem5() {
        return jMenuItem5;
    }

    /**
     * @param jMenuItem5 the jMenuItem5 to set
     */
    public void setjMenuItem5(javax.swing.JMenuItem jMenuItem5) {
        this.jMenuItem5 = jMenuItem5;
    }

    /**
     * @return the jMenuItem6
     */
    public javax.swing.JMenuItem getjMenuItem6() {
        return STLEtagere;
    }

    /**
     * @param jMenuItem6 the jMenuItem6 to set
     */
    public void setjMenuItem6(javax.swing.JMenuItem jMenuItem6) {
        this.STLEtagere = jMenuItem6;
    }

    /**
     * @return the jMenuItem7
     */
    public javax.swing.JMenuItem getjMenuItem7() {
        return STLPiecesIndividuelles;
    }

    /**
     * @param jMenuItem7 the jMenuItem7 to set
     */
    public void setjMenuItem7(javax.swing.JMenuItem jMenuItem7) {
        this.STLPiecesIndividuelles = jMenuItem7;
    }

    /**
     * @return the jRadioButton1
     */
    public javax.swing.JRadioButton getjRadioButton1() {
        return Metrique_Button;
    }

    /**
     * @param jRadioButton1 the jRadioButton1 to set
     */
    public void setjRadioButton1(javax.swing.JRadioButton jRadioButton1) {
        this.Metrique_Button = jRadioButton1;
    }

    /**
     * @return the jRadioButton2
     */
    public javax.swing.JRadioButton getjRadioButton2() {
        return Imperial_Button;
    }

    /**
     * @param jRadioButton2 the jRadioButton2 to set
     */
    public void setjRadioButton2(javax.swing.JRadioButton jRadioButton2) {
        this.Imperial_Button = jRadioButton2;
    }

    /**
     * @return the jRadioButton3
     */
    public javax.swing.JRadioButton getjRadioButton3() {
        return PerimetreDouble_Radio;
    }

    /**
     * @param jRadioButton3 the jRadioButton3 to set
     */
    public void setjRadioButton3(javax.swing.JRadioButton jRadioButton3) {
        this.PerimetreDouble_Radio = jRadioButton3;
    }

    /**
     * @return the jRadioButton4
     */
    public javax.swing.JRadioButton getjRadioButton4() {
        return PerimatreTriple_Radio;
    }

    /**
     * @param jRadioButton4 the jRadioButton4 to set
     */
    public void setjRadioButton4(javax.swing.JRadioButton jRadioButton4) {
        this.PerimatreTriple_Radio = jRadioButton4;
    }
    
    public void enableRedoButton(boolean canRedo) {
        Redo_Button.setEnabled(canRedo);
    }
}
