package UI;

import Main_Package.Controleur;
import java.awt.event.KeyEvent;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SABOU350
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        HauteurPieceSelecrtionneField = new javax.swing.JTextField();
        LargeurPieceSelecrtionneField = new javax.swing.JTextField();
        ProfondeurPieceSelecrtionneField = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        Metrique_Button = new javax.swing.JRadioButton();
        Imperial_Button = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        AfficheurContainer = new javax.swing.JPanel();
        afficheur = new UI.AfficheurEtagere2D();
        jLabel1 = new javax.swing.JLabel();
        Profondeur_Label = new javax.swing.JLabel();
        Hauteur_Label = new javax.swing.JLabel();
        Largeur_Label = new javax.swing.JLabel();
        Hauteur_Textfield = new javax.swing.JTextField();
        Largeur_TextField = new javax.swing.JTextField();
        Profondeur_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        HPiece_Cmlabel = new javax.swing.JLabel();
        LPiece_Cmlabel = new javax.swing.JLabel();
        PPiece_Cmlabel = new javax.swing.JLabel();
        Largeur_Cmlabel = new javax.swing.JLabel();
        Profondeur_CMlabel = new javax.swing.JLabel();
        Hauteur_Cmlabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuBtnNouveau = new javax.swing.JMenuItem();
        MenuSauvegarder = new javax.swing.JMenuItem();
        MenuCharger = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("3Dtagère");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);
        setName("MainWindow"); // NOI18N

        jButton7.setText("Perimetre triple ou double");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Verticale");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton5.setText("Supprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        HauteurPieceSelecrtionneField.setToolTipText("");

        ProfondeurPieceSelecrtionneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfondeurPieceSelecrtionneFieldActionPerformed(evt);
            }
        });
        ProfondeurPieceSelecrtionneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProfondeurPieceSelecrtionneFieldKeyPressed(evt);
            }
        });

        jButton22.setText("Undo");
        jButton22.setActionCommand("Imperial ou metrique");
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton22MouseClicked(evt);
            }
        });
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton21.setText("Redo");
        jButton21.setActionCommand("Imperial ou metrique");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Double");
        jRadioButton3.setToolTipText("");
        jRadioButton3.setActionCommand("");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Triple");
        jRadioButton4.setToolTipText("");
        jRadioButton4.setActionCommand("");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(Metrique_Button);
        Metrique_Button.setSelected(true);
        Metrique_Button.setText("Métrique");
        Metrique_Button.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Metrique_ButtonStateChanged(evt);
            }
        });
        Metrique_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Metrique_ButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(Imperial_Button);
        Imperial_Button.setText("Impérial");
        Imperial_Button.setToolTipText("");
        Imperial_Button.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Imperial_ButtonStateChanged(evt);
            }
        });
        Imperial_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imperial_ButtonActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Panneau de fond");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Dépasse");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pièce 1", "Pièce 2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton6.setText("Horizontale");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextPane1.setText("Liste de pièces");
        jScrollPane2.setViewportView(jTextPane1);

        AfficheurContainer.setBackground(new java.awt.Color(255, 255, 255));
        AfficheurContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Controleur.getInstance().setAfficheur(afficheur);
        afficheur.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout afficheurLayout = new javax.swing.GroupLayout(afficheur);
        afficheur.setLayout(afficheurLayout);
        afficheurLayout.setHorizontalGroup(
            afficheurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1141, Short.MAX_VALUE)
        );
        afficheurLayout.setVerticalGroup(
            afficheurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AfficheurContainerLayout = new javax.swing.GroupLayout(AfficheurContainer);
        AfficheurContainer.setLayout(AfficheurContainerLayout);
        AfficheurContainerLayout.setHorizontalGroup(
            AfficheurContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfficheurContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(afficheur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AfficheurContainerLayout.setVerticalGroup(
            AfficheurContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfficheurContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(afficheur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("Dimension de l'étagere");

        Profondeur_Label.setText("Profondeur");

        Hauteur_Label.setText("Hauteur");

        Largeur_Label.setText("Largeur");

        Hauteur_Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hauteur_TextfieldActionPerformed(evt);
            }
        });
        Hauteur_Textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Hauteur_TextfieldKeyPressed(evt);
            }
        });

        Largeur_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Largeur_TextFieldActionPerformed(evt);
            }
        });
        Largeur_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Largeur_TextFieldKeyPressed(evt);
            }
        });

        jLabel2.setText("Hauteur");

        jLabel3.setText("Largeur");

        jLabel4.setText("Profondeur");

        jLabel5.setText("Dimensions de la pièce sélectionnée");

        HPiece_Cmlabel.setText("Cm");

        LPiece_Cmlabel.setText("Cm");

        PPiece_Cmlabel.setText("Cm");

        Largeur_Cmlabel.setText("Cm");

        Profondeur_CMlabel.setText("Cm");

        Hauteur_Cmlabel.setText("Cm");

        jMenu1.setText("Fichier");

        MenuBtnNouveau.setText("Nouveau");
        MenuBtnNouveau.setActionCommand("");
        MenuBtnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBtnNouveauActionPerformed(evt);
            }
        });
        jMenu1.add(MenuBtnNouveau);

        MenuSauvegarder.setText("Sauvegarder");
        MenuSauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSauvegarderActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSauvegarder);

        MenuCharger.setText("Charger");
        MenuCharger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuChargerActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCharger);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exporter");

        jMenuItem4.setText("Liste des pièces");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Plan de coupe");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Modèle 3D de l'étagère");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Modèle 3D des pièces");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(AfficheurContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Largeur_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Hauteur_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                                    .addComponent(Profondeur_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Profondeur_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hauteur_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Largeur_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Largeur_Cmlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(8, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Profondeur_CMlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(8, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Hauteur_Cmlabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Metrique_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(HauteurPieceSelecrtionneField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LargeurPieceSelecrtionneField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ProfondeurPieceSelecrtionneField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(HPiece_Cmlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PPiece_Cmlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LPiece_Cmlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(50, 50, 50))
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Imperial_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3)))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(269, 269, 269)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1319, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton4)
                                    .addComponent(Metrique_Button))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Imperial_Button)
                                    .addComponent(jRadioButton3))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Hauteur_Label)
                                    .addComponent(Hauteur_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hauteur_Cmlabel))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Largeur_Label)
                                            .addComponent(Largeur_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(Largeur_Cmlabel)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Profondeur_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Profondeur_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Profondeur_CMlabel))
                                .addGap(199, 199, 199)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2)
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 943, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(HauteurPieceSelecrtionneField)
                                        .addComponent(HPiece_Cmlabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LargeurPieceSelecrtionneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(LPiece_Cmlabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ProfondeurPieceSelecrtionneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(PPiece_Cmlabel)))
                            .addComponent(AfficheurContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(751, 751, 751)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(609, 609, 609)))
        );

        Hauteur_Label.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getHauteur_Label() {
        return Hauteur_Label;
    }

    public void setHauteur_Label(JLabel Hauteur_Label) {
        this.Hauteur_Label = Hauteur_Label;
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void Metrique_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Metrique_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Metrique_ButtonActionPerformed

    private void Imperial_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imperial_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Imperial_ButtonActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void MenuBtnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBtnNouveauActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
             @Override
             public void run() {
                promptCreerEtagere();
             }
        });
    }//GEN-LAST:event_MenuBtnNouveauActionPerformed

    private void Largeur_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Largeur_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Largeur_TextFieldActionPerformed

    private void Hauteur_TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hauteur_TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hauteur_TextfieldActionPerformed

    private void ProfondeurPieceSelecrtionneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfondeurPieceSelecrtionneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfondeurPieceSelecrtionneFieldActionPerformed

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        if(jCheckBox2.isSelected()){
            Controleur.getInstance().setDepasse(true);
        }
        if(jCheckBox2.isSelected()){
            Controleur.getInstance().setDepasse(false);        
        }
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    private void Hauteur_TextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Hauteur_TextfieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Controleur.getInstance().setEtagereHauteur(Double.parseDouble(getHauteur_Textfield().getText()));
            Controleur.getInstance().getAfficheur().redraw();
        }
    }//GEN-LAST:event_Hauteur_TextfieldKeyPressed

    private void Largeur_TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Largeur_TextFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Controleur.getInstance().setEtagereLargeur(Double.parseDouble(getLargeur_TextField().getText()));
            Controleur.getInstance().getAfficheur().redraw();
        }
    }//GEN-LAST:event_Largeur_TextFieldKeyPressed

    private void ProfondeurPieceSelecrtionneFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProfondeurPieceSelecrtionneFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Controleur.getInstance().setEtagereProfondeur(Double.parseDouble(getLargeur_TextField().getText()));
            Controleur.getInstance().getAfficheur().redraw();
        }
    }//GEN-LAST:event_ProfondeurPieceSelecrtionneFieldKeyPressed

    private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
        Controleur.getInstance().undo();
        System.out.println("UI.GUI.jButton22MouseClicked()");
    }//GEN-LAST:event_jButton22MouseClicked

    private void Metrique_ButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Metrique_ButtonStateChanged
        if(Metrique_Button.isSelected()){
            Hauteur_Cmlabel.setText("Cm");
            Largeur_Cmlabel.setText("Cm");
            Profondeur_CMlabel.setText("Cm");
            HPiece_Cmlabel.setText("Cm");
            LPiece_Cmlabel.setText("Cm");
            PPiece_Cmlabel.setText("Cm");
        }
    }//GEN-LAST:event_Metrique_ButtonStateChanged

    private void Imperial_ButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Imperial_ButtonStateChanged
        if(Imperial_Button.isSelected()){
            Hauteur_Cmlabel.setText("Po");
            Largeur_Cmlabel.setText("Po");
            Profondeur_CMlabel.setText("Po");
            HPiece_Cmlabel.setText("Po");
            LPiece_Cmlabel.setText("Po");
            PPiece_Cmlabel.setText("Po");
        }
    }//GEN-LAST:event_Imperial_ButtonStateChanged

    private void MenuSauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSauvegarderActionPerformed
        Controleur.getInstance().sauvegarderEtagere();
    }//GEN-LAST:event_MenuSauvegarderActionPerformed

    private void MenuChargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuChargerActionPerformed
        Controleur.getInstance().chargerEtagere();
    }//GEN-LAST:event_MenuChargerActionPerformed
    public static void promptCreerEtagere() {
        CreateNewEtagereWindow popup2 = new CreateNewEtagereWindow();
        popup2.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                GUI gui = new GUI();
                gui.setVisible(true);
                Controleur.getInstance().setVue(gui);
                promptCreerEtagere();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AfficheurContainer;
    private javax.swing.JLabel HPiece_Cmlabel;
    private javax.swing.JTextField HauteurPieceSelecrtionneField;
    private javax.swing.JLabel Hauteur_Cmlabel;
    private javax.swing.JLabel Hauteur_Label;
    private javax.swing.JTextField Hauteur_Textfield;
    private javax.swing.JRadioButton Imperial_Button;
    private javax.swing.JLabel LPiece_Cmlabel;
    private javax.swing.JTextField LargeurPieceSelecrtionneField;
    private javax.swing.JLabel Largeur_Cmlabel;
    private javax.swing.JLabel Largeur_Label;
    private javax.swing.JTextField Largeur_TextField;
    private javax.swing.JMenuItem MenuBtnNouveau;
    private javax.swing.JMenuItem MenuCharger;
    private javax.swing.JMenuItem MenuSauvegarder;
    private javax.swing.JRadioButton Metrique_Button;
    private javax.swing.JLabel PPiece_Cmlabel;
    private javax.swing.JTextField ProfondeurPieceSelecrtionneField;
    private javax.swing.JLabel Profondeur_CMlabel;
    private javax.swing.JLabel Profondeur_Label;
    private javax.swing.JTextField Profondeur_TextField;
    private UI.AfficheurEtagere2D afficheur;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    public JTextField getHauteur_Textfield() {
        return Hauteur_Textfield;
    }
    

    public void setHauteur_Textfield(JTextField Hauteur_Textfield) {
        this.Hauteur_Textfield = Hauteur_Textfield;
    }

    public JTextField getLargeur_TextField() {
        return Largeur_TextField;
    }

    public void setLargeur_TextField(JTextField Largeur_TextField) {
        this.Largeur_TextField = Largeur_TextField;
    }

    public JTextField getProfondeur_TextField() {
        return Profondeur_TextField;
    }

    public void setProfondeur_TextField(JTextField Profondeur_TextField) {
        this.Profondeur_TextField = Profondeur_TextField;
    }

    /**
     * @return the AfficheurContainer
     */
    public javax.swing.JPanel getAfficheurContainer() {
        return AfficheurContainer;
    }

    /**
     * @param AfficheurContainer the AfficheurContainer to set
     */
    public void setAfficheurContainer(javax.swing.JPanel AfficheurContainer) {
        this.AfficheurContainer = AfficheurContainer;
    }

    /**
     * @return the EpaisseurPieceSelecrtionneField
     */
    public javax.swing.JTextField getProfondeurPieceSelecrtionneField() {
        return ProfondeurPieceSelecrtionneField;
    }

    /**
     * @param EpaisseurPieceSelecrtionneField the EpaisseurPieceSelecrtionneField to set
     */
    public void setProfondeurPieceSelecrtionneField(javax.swing.JTextField EpaisseurPieceSelecrtionneField) {
        this.ProfondeurPieceSelecrtionneField = EpaisseurPieceSelecrtionneField;
    }

    /**
     * @return the HauteurPieceSelecrtionneField
     */
    public javax.swing.JTextField getHauteurPieceSelecrtionneField() {
        return HauteurPieceSelecrtionneField;
    }

    /**
     * @param HauteurPieceSelecrtionneField the HauteurPieceSelecrtionneField to set
     */
    public void setHauteurPieceSelecrtionneField(javax.swing.JTextField HauteurPieceSelecrtionneField) {
        this.HauteurPieceSelecrtionneField = HauteurPieceSelecrtionneField;
    }

    /**
     * @return the LargeurPieceSelecrtionneField
     */
    public javax.swing.JTextField getLargeurPieceSelecrtionneField() {
        return LargeurPieceSelecrtionneField;
    }

    /**
     * @param LargeurPieceSelecrtionneField the LargeurPieceSelecrtionneField to set
     */
    public void setLargeurPieceSelecrtionneField(javax.swing.JTextField LargeurPieceSelecrtionneField) {
        this.LargeurPieceSelecrtionneField = LargeurPieceSelecrtionneField;
    }

    /**
     * @return the Largeur_Label
     */
    public javax.swing.JLabel getLargeur_Label() {
        return Largeur_Label;
    }

    /**
     * @param Largeur_Label the Largeur_Label to set
     */
    public void setLargeur_Label(javax.swing.JLabel Largeur_Label) {
        this.Largeur_Label = Largeur_Label;
    }

    /**
     * @return the MenuBtnNouveau
     */
    public javax.swing.JMenuItem getMenuBtnNouveau() {
        return MenuBtnNouveau;
    }

    /**
     * @param MenuBtnNouveau the MenuBtnNouveau to set
     */
    public void setMenuBtnNouveau(javax.swing.JMenuItem MenuBtnNouveau) {
        this.MenuBtnNouveau = MenuBtnNouveau;
    }

    /**
     * @return the Profondeur_Label
     */
    public javax.swing.JLabel getProfondeur_Label() {
        return Profondeur_Label;
    }

    /**
     * @param Profondeur_Label the Profondeur_Label to set
     */
    public void setProfondeur_Label(javax.swing.JLabel Profondeur_Label) {
        this.Profondeur_Label = Profondeur_Label;
    }

    /**
     * @return the afficheur
     */
    public UI.AfficheurEtagere2D getAfficheur() {
        return afficheur;
    }

    /**
     * @param afficheur the afficheur to set
     */
    public void setAfficheur(UI.AfficheurEtagere2D afficheur) {
        this.afficheur = afficheur;
    }

    /**
     * @return the buttonGroup1
     */
    public javax.swing.ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    /**
     * @param buttonGroup1 the buttonGroup1 to set
     */
    public void setButtonGroup1(javax.swing.ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    /**
     * @return the buttonGroup2
     */
    public javax.swing.ButtonGroup getButtonGroup2() {
        return buttonGroup2;
    }

    /**
     * @param buttonGroup2 the buttonGroup2 to set
     */
    public void setButtonGroup2(javax.swing.ButtonGroup buttonGroup2) {
        this.buttonGroup2 = buttonGroup2;
    }

    /**
     * @return the jButton21
     */
    public javax.swing.JButton getjButton21() {
        return jButton21;
    }

    /**
     * @param jButton21 the jButton21 to set
     */
    public void setjButton21(javax.swing.JButton jButton21) {
        this.jButton21 = jButton21;
    }

    /**
     * @return the jButton22
     */
    public javax.swing.JButton getjButton22() {
        return jButton22;
    }

    /**
     * @param jButton22 the jButton22 to set
     */
    public void setjButton22(javax.swing.JButton jButton22) {
        this.jButton22 = jButton22;
    }

    /**
     * @return the jButton5
     */
    public javax.swing.JButton getjButton5() {
        return jButton5;
    }

    /**
     * @param jButton5 the jButton5 to set
     */
    public void setjButton5(javax.swing.JButton jButton5) {
        this.jButton5 = jButton5;
    }

    /**
     * @return the jButton6
     */
    public javax.swing.JButton getjButton6() {
        return jButton6;
    }

    /**
     * @param jButton6 the jButton6 to set
     */
    public void setjButton6(javax.swing.JButton jButton6) {
        this.jButton6 = jButton6;
    }

    /**
     * @return the jButton7
     */
    public javax.swing.JButton getjButton7() {
        return jButton7;
    }

    /**
     * @param jButton7 the jButton7 to set
     */
    public void setjButton7(javax.swing.JButton jButton7) {
        this.jButton7 = jButton7;
    }

    /**
     * @return the jButton8
     */
    public javax.swing.JButton getjButton8() {
        return jButton8;
    }

    /**
     * @param jButton8 the jButton8 to set
     */
    public void setjButton8(javax.swing.JButton jButton8) {
        this.jButton8 = jButton8;
    }

    /**
     * @return the jCheckBox1
     */
    public javax.swing.JCheckBox getjCheckBox1() {
        return jCheckBox1;
    }

    /**
     * @param jCheckBox1 the jCheckBox1 to set
     */
    public void setjCheckBox1(javax.swing.JCheckBox jCheckBox1) {
        this.jCheckBox1 = jCheckBox1;
    }

    /**
     * @return the jCheckBox2
     */
    public javax.swing.JCheckBox getjCheckBox2() {
        return jCheckBox2;
    }

    /**
     * @param jCheckBox2 the jCheckBox2 to set
     */
    public void setjCheckBox2(javax.swing.JCheckBox jCheckBox2) {
        this.jCheckBox2 = jCheckBox2;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jList1
     */
    public javax.swing.JList<String> getjList1() {
        return jList1;
    }

    /**
     * @param jList1 the jList1 to set
     */
    public void setjList1(javax.swing.JList<String> jList1) {
        this.jList1 = jList1;
    }

    /**
     * @return the jMenu1
     */
    public javax.swing.JMenu getjMenu1() {
        return jMenu1;
    }

    /**
     * @param jMenu1 the jMenu1 to set
     */
    public void setjMenu1(javax.swing.JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    /**
     * @return the jMenu2
     */
    public javax.swing.JMenu getjMenu2() {
        return jMenu2;
    }

    /**
     * @param jMenu2 the jMenu2 to set
     */
    public void setjMenu2(javax.swing.JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    /**
     * @return the jMenuBar1
     */
    public javax.swing.JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    /**
     * @param jMenuBar1 the jMenuBar1 to set
     */
    public void setjMenuBar1(javax.swing.JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    /**
     * @return the jMenuItem1
     */
    public javax.swing.JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    /**
     * @param jMenuItem1 the jMenuItem1 to set
     */
    public void setjMenuItem1(javax.swing.JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    /**
     * @return the jMenuItem3
     */
    public javax.swing.JMenuItem getjMenuItem3() {
        return MenuSauvegarder;
    }

    /**
     * @param jMenuItem3 the jMenuItem3 to set
     */
    public void setjMenuItem3(javax.swing.JMenuItem jMenuItem3) {
        this.MenuSauvegarder = jMenuItem3;
    }

    /**
     * @return the jMenuItem4
     */
    public javax.swing.JMenuItem getjMenuItem4() {
        return jMenuItem4;
    }

    /**
     * @param jMenuItem4 the jMenuItem4 to set
     */
    public void setjMenuItem4(javax.swing.JMenuItem jMenuItem4) {
        this.jMenuItem4 = jMenuItem4;
    }

    /**
     * @return the jMenuItem5
     */
    public javax.swing.JMenuItem getjMenuItem5() {
        return jMenuItem5;
    }

    /**
     * @param jMenuItem5 the jMenuItem5 to set
     */
    public void setjMenuItem5(javax.swing.JMenuItem jMenuItem5) {
        this.jMenuItem5 = jMenuItem5;
    }

    /**
     * @return the jMenuItem6
     */
    public javax.swing.JMenuItem getjMenuItem6() {
        return jMenuItem6;
    }

    /**
     * @param jMenuItem6 the jMenuItem6 to set
     */
    public void setjMenuItem6(javax.swing.JMenuItem jMenuItem6) {
        this.jMenuItem6 = jMenuItem6;
    }

    /**
     * @return the jMenuItem7
     */
    public javax.swing.JMenuItem getjMenuItem7() {
        return jMenuItem7;
    }

    /**
     * @param jMenuItem7 the jMenuItem7 to set
     */
    public void setjMenuItem7(javax.swing.JMenuItem jMenuItem7) {
        this.jMenuItem7 = jMenuItem7;
    }

    /**
     * @return the jRadioButton1
     */
    public javax.swing.JRadioButton getjRadioButton1() {
        return Metrique_Button;
    }

    /**
     * @param jRadioButton1 the jRadioButton1 to set
     */
    public void setjRadioButton1(javax.swing.JRadioButton jRadioButton1) {
        this.Metrique_Button = jRadioButton1;
    }

    /**
     * @return the jRadioButton2
     */
    public javax.swing.JRadioButton getjRadioButton2() {
        return Imperial_Button;
    }

    /**
     * @param jRadioButton2 the jRadioButton2 to set
     */
    public void setjRadioButton2(javax.swing.JRadioButton jRadioButton2) {
        this.Imperial_Button = jRadioButton2;
    }

    /**
     * @return the jRadioButton3
     */
    public javax.swing.JRadioButton getjRadioButton3() {
        return jRadioButton3;
    }

    /**
     * @param jRadioButton3 the jRadioButton3 to set
     */
    public void setjRadioButton3(javax.swing.JRadioButton jRadioButton3) {
        this.jRadioButton3 = jRadioButton3;
    }

    /**
     * @return the jRadioButton4
     */
    public javax.swing.JRadioButton getjRadioButton4() {
        return jRadioButton4;
    }

    /**
     * @param jRadioButton4 the jRadioButton4 to set
     */
    public void setjRadioButton4(javax.swing.JRadioButton jRadioButton4) {
        this.jRadioButton4 = jRadioButton4;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jScrollPane2
     */
    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * @param jScrollPane2 the jScrollPane2 to set
     */
    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

   

    /**
     * @return the jTextPane1
     */
    public javax.swing.JTextPane getjTextPane1() {
        return jTextPane1;
    }

    /**
     * @param jTextPane1 the jTextPane1 to set
     */
    public void setjTextPane1(javax.swing.JTextPane jTextPane1) {
        this.jTextPane1 = jTextPane1;
    }

    
    
}
